---
abstract: 'Apply iTunes-like metadata to an mp4 file.'
author:
  - 'Andrew Jones <andrew@arjones.co.uk>'
build_requires:
  App::Cmd::Tester: 0
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-MP4Meta
requires:
  App::Cmd::Setup: 0
  AtomicParsley::Command: 0
  AtomicParsley::Command::Tags: 0
  File::Copy: 0
  File::Spec: 0
  File::Temp: 0
  HTML::TreeBuilder::XPath: 0
  IMDB::Film: 0
  LWP::UserAgent: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/andrewrjones/perl5-App-MP4Meta/issues
  homepage: https://github.com/andrewrjones/perl5-App-MP4Meta
  repository: https://github.com/andrewrjones/perl5-App-MP4Meta.git
version: 1.113520
